[tool.commitizen]
bump_message = "chore: Release $new_version"
tag_format = "$version"
version = "1.5.3"
version_files = [
    "README.md",
    "pyproject.toml:version",
    "docs/index.html",
    "src/REST/version.py:__version__"
]
