#!/usr/bin/env bash

set -e

### globals ####################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

### run libdoc in docker #######################################################

RUN_ARGS="--entrypoint entrypoint -v $this_path:/home/robot" \
  "$this_path/rfdocker" python -m robot.libdoc REST:: index.html
