#!/usr/bin/env bash

set -e

### consts #####################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
x
## variables ###################################################################

registry_url="$1"

### release ####################################################################

version=$(RUN_ARGS="--entrypoint entrypoint" \
  "$this_path/rfdocker" python -c "import REST; print(REST.__version__, end='')")
version=$(echo "$version" | tail -n1)

if [ -z "$registry_url" ]; then
  echo "Usage: $0 REGISTRY_URL"
  echo ""
  echo "  e.g.: $0 https://your.private.registry.com/restinstance"
  echo
  echo "  would tag and push the image as both latest and $version"
  exit 64
fi

echo "### Tagging image 'rfdocker:restinstance' to '$registry_url:$version'"
docker tag "rfdocker:restinstance" "$registry_url:$version"

echo "### Pushing image 'restinstance:$version' to registry..."
docker push "$registry_url:$version"

echo "### Tagging image 'rfdocker:restinstance' to '$registry_url:latest'"
docker tag "rfdocker:restinstance" "$registry_url:latest"

echo "### Pushing image 'rfdocker:restinstance' to '$registry_url:latest'"
docker push "$registry_url:latest"
