#!/bin/bash

# create the user
if ! id "$UNAME" >/dev/null 2>&1; then
  echo "$UNAME:x:$HOST_UID:$HOST_GID:$UNAME,,,:$UHOME:$SHELL" >> /etc/passwd
  echo "$UNAME::17032:0:99999:7:::" >> /etc/shadow
fi

# add the user to sudoers
if [ ! -f "/etc/sudoers.d/$UNAME" ]; then
  echo "$UNAME ALL=(ALL) NOPASSWD: ALL" > "/etc/sudoers.d/$UNAME"
  chmod 0440 "/etc/sudoers.d/$UNAME"
fi

# create the group for the user
egrep -i "^$GNAME" /etc/group;
if [ $? -ne 0 ]; then
  echo "$GNAME:x:$HOST_GID:$UNAME" >> /etc/group
fi

# chown the existing, or create a new home directory for the user
if [ -d "$UHOME" ]; then
  home_owner="$(stat -c '%U' $UHOME)"
  if [ $(id -u $UNAME) -ne $(id -u $home_owner) ]; then
    chown "$HOST_UID":"$HOST_GID" -R $UHOME
  fi
else
  mkdir -p "$UHOME"
  chown "$HOST_UID":"$HOST_GID" "$UHOME"
fi

# execute command as the user
su-exec "$UNAME" "$@"
