#!/usr/bin/env bash

set -e

### constants ##################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

### variables ##################################################################

: ${IMAGE_NAME:="${BUILD_DIR##*/}"}
: ${FROM_IMAGE_TAG:="latest"}

: ${REGISTRY_URL:=""}
: ${REGISTRY_USERNAME:="$USER"}

: ${IMAGE_REF:="${REGISTRY_URL}$REGISTRY_USERNAME/${IMAGE_NAME}"}
: ${TO_IMAGE_TAG:="$(date +%y.%m.%d.%H%M)"}

### tag and push ###############################################################

# Docker image is part of the repository, and the repository must be in downcase
declare -l IMAGE_NAME
IMAGE_NAME=$IMAGE_NAME

docker login "$REGISTRY_URL"

docker tag "$IMAGE_NAME:$FROM_IMAGE_TAG" "$IMAGE_REF:$TO_IMAGE_TAG"
docker push "$IMAGE_REF:$TO_IMAGE_TAG"

docker tag "$IMAGE_NAME:$FROM_IMAGE_TAG" "$IMAGE_REF:latest"
docker push "$IMAGE_REF:latest"
