#!/usr/bin/env bash

# https://github.com/asyrjasalo/restinstance
# https://hub.docker.com/r/asyrjasalo/restinstance

set -e

### globals ####################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root_path="$this_path/.."

### settings ###################################################################

: ${BUILD_NAME="restinstance"}
: ${MR_NETWORK:="testapi_default"}
: ${RF_ARGS:="--randomize all"}

### main #######################################################################

# https://github.com/asyrjasalo/mounterest
HOST_UID=$(id -u) HOST_GID=$(id -g) \
  docker-compose up -d

# https://github.com/asyrjasalo/rfdocker
BUILD_NAME="$BUILD_NAME" RUN_ARGS="--network=$MR_NETWORK" \
  "$root_path/rfdocker" \
    $RF_ARGS "${@:-tests}"
