#!/usr/bin/env bash

set -e

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root_path="$this_path/.."

# https://github.com/asyrjasalo/mounterest
docker rm --force mounterest 1>/dev/null
HOST_UID=$(id -u) HOST_GID=$(id -g) \
  docker-compose up -d

# https://github.com/asyrjasalo/rfdocker
RUN_ARGS="--network=testapi_default" \
  "$root_path/rfdocker" \
    --randomize all "${@:-tests}"
