#!/usr/bin/env bash

# https://github.com/asyrjasalo/restinstance
# https://hub.docker.com/r/asyrjasalo/restinstance

set -e

### globals ####################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root_path="$this_path/.."

### settings ###################################################################

: ${BUILD_NAME="restinstance"}
: ${MB_PORT:=2525}
: ${MR_ARGS:="--loglevel info"}
: ${MR_IMAGE_LABEL:="asyrjasalo/mounterest"}
: ${MR_IMAGE_TAG:="0.1.2"}
: ${MR_NETWORK:=${PWD##*/}_default}
: ${MR_PORT:=8273}
: ${RF_ARGS:="--randomize all"}

### helpers ####################################################################

cleanup_mounterest() {
  docker rm --force mounterest 1>/dev/null
}

_reset_mounterest() {
  docker run --rm -t -i --network="$MR_NETWORK" \
    alpine/httpie delete http://mounterest:$MR_PORT/state 1>/dev/null && \
  echo "### Mounterest state cleaned"
}

### main #######################################################################

# https://github.com/asyrjasalo/mounterest
trap "cleanup_mounterest &" SIGINT SIGTERM
HOST_UID=$(id -u) HOST_GID=$(id -g) \
MB_PORT=$MB_PORT MR_ARGS=$MR_ARGS MR_IMAGE_LABEL=$MR_IMAGE_LABEL \
MR_IMAGE_TAG=$MR_IMAGE_TAG MR_NETWORK=$MR_NETWORK MR_PORT=$MR_PORT \
  docker-compose up -d
_reset_mounterest  || true

# https://github.com/asyrjasalo/rfdocker
BUILD_NAME="$BUILD_NAME" \
RUN_ARGS="--network=$MR_NETWORK -e MB_PORT=$MB_PORT -e MR_PORT=$MR_PORT" \
  "$root_path/rfdocker" \
    $RF_ARGS "${@:-tests}"