#!/usr/bin/env bash

set -e

### globals ####################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_path="$this_path/.."

### run libdoc in docker #######################################################

RUN_ARGS="--entrypoint entrypoint -v $repo_path/docs:/home/robot/docs" \
  "$repo_path/rfdocker" python -m robot.libdoc REST docs/index.html
