#!/usr/bin/env bash

set -e

### consts #####################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_path="$this_path/.."

## variables ###################################################################

registry_url="$1"
version=$(cat "$repo_path/src/REST/version.py" | cut -d"'" -f2 | sed "s/'//g")

### release ####################################################################

if [ -z "$registry_url" ]; then
  echo "Usage: $0 REGISTRY_URL"
  echo ""
  echo "  e.g.: $0 https://your.registry.com:5000/restinstance"
  exit 64
fi

echo "### Tagging image 'rfdocker:restinstance' to '$registry_url:$version'"
docker tag "rfdocker:restinstance" "$registry_url:$version"

echo "### Pushing image 'restinstance:$version' to registry..."
docker push "$registry_url:$version"

echo "### Tagging image 'rfdocker:restinstance' to '$registry_url:latest'"
docker tag "rfdocker:restinstance" "$registry_url:latest"

echo "### Pushing image 'rfdocker:restinstance' to '$registry_url:latest'"
docker push "$registry_url:latest"
