#!/usr/bin/env bash

set -e

### consts #####################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_path="$this_path/.."

### release ####################################################################

export PATH="$HOME/.local/bin:$PATH"
pip install --user --upgrade twine wheel
rm -rf "$repo_path/dist" "$repo_path/build" \
    "$repo_path/src/RESTinstance.egg-info"
python "$repo_path/setup.py" install --user --force
python "$repo_path/setup.py" sdist bdist_wheel
twine upload "$repo_path/dist/*"
