#!/usr/bin/env bash

set -e

### consts #####################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_path="$this_path/.."
venv_path="$repo_path/.venvs/release"

### release ####################################################################

rm -rf "$venv_path" "$repo_path/dist" "$repo_path/build" \
    "$repo_path/src/RESTinstance.egg-info"

export PATH="$HOME/.local/bin:$PATH"
virtualenv --version >/dev/null || pip install --user virtualenv

virtualenv "$venv_path"
source "$venv_path/bin/activate"

pip install "$repo_path"

pip install wheel
python "$repo_path/setup.py" sdist bdist_wheel

pip install twine
twine upload "$repo_path/dist/*"
