#!/usr/bin/env bash

set -e

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root_path="$this_path/.."

# https://github.com/asyrjasalo/mounterest
HOST_UID=$(id -u) HOST_GID=$(id -g) \
  docker-compose -f "$root_path/testapi/docker-compose.yml" \
    up -d --force-recreate

# https://github.com/asyrjasalo/rfdocker
BUILD_DIR="$root_path" RUN_ARGS="--network=host" \
  "$root_path/rfdocker" \
    --randomize all "${@:-tests}"
